version: '3.1'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_USER=ampio
      - INFLUXDB_USER_PASSWORD=ampio
    volumes:
      - influxdb-storage:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana

  nodered:
    image: nodered/node-red:2.0.5
    container_name: node-red
    ports:
      - "1880:1880"
    depends_on:
      - influxdb
    volumes:
      - nodered-storage:/data

volumes:
  influxdb-storage:
  grafana-storage:
  nodered-storage: