version: "3.8"

services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - .env
    volumes:
      - influxdb-storage:/var/lib/influxdb
    labels:
      - docker-volume-backup.stop-during-backup=true

  grafana:
    image: grafana/grafana:8.2.4
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana

  nodered:
    image: kadzaa/private:latest
    container_name: node-red
    ports:
      - "1880:1880"
    env_file:
      - .env
    depends_on:
      - influxdb

  backup:
    image: offen/docker-volume-backup:latest
    container_name: backup
    environment:
        BACKUP_FILENAME: backup.tar.gz
        BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
    volumes:
      - /home/luke/repos/home-automation/src/bkp:/archive
      - influxdb-storage:/backup/influxdb-backup:ro
      - grafana-storage:/backup/grafana-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  influxdb-storage:
  grafana-storage:
  nodered-storage:
